# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(1, 'scheduled'), (2, 'success'), (3, 'failure')], default=1),
        ),
    ]
